name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Cambia esto según la versión de Java que necesites

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Asegúrate de agregar tu token en los secretos del repositorio
        run: mvn sonar:sonar -Dsonar.projectKey=mi-proyecto -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
